---

- name: Import rabbitmq PGP key
  apt_key:
    url: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    state: present

- apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present

- name: Add rabbitmq repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq-erlang/debian focal erlang-22.x"
    update_cache: true

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present

