- name: Install Server Density agent
  apt:
    name: apt-transport-https
    state: present

- shell: curl -L https://archive.serverdensity.com/sd-packaging-public.key | sudo apt-key add -

- shell: echo "deb https://archive.serverdensity.com/ubuntu/ focal main" > /etc/apt/sources.list.d/sd-agent.list

- apt:
   update_cache: yes

- apt:
    name: sd-agent
    state: present

