template_path: dev/bastionHost.yaml
dependencies:
  - dev/eks.yaml
parameters:
  InstanceImage: ami-087855b6c8b59a9e4
  SSHKey: OTF-Viktor-Georgiev
  VmType: t2.micro
  SubnetPublicId: !stack_output dev/vpc.yaml::SubnetPublic
  BastionSecurityGroup: !stack_output dev/vpc.yaml::BastionSecurityGroup
  ClusterName: development
  awsConfig: !file_contents /root/.aws/config
  awsCredentials: !file_contents /root/.aws/credentials
