template_path: dev/bastionHost.yaml
dependencies:
  - dev/eks.yaml
parameters:
  InstanceImage: "{{ stack_group_config.bastion_image_id }}"
  SSHKey: "{{ stack_group_config.ssh_key_name }}"
  VmType: "{{ stack_group_config.bastion_instance_type }}"
  SubnetPublicId: !stack_output dev/vpc.yaml::SubnetPublic
  BastionSecurityGroup: !stack_output dev/vpc.yaml::BastionSecurityGroup
  ClusterName: "{{ stack_group_config.cluster_name }}"
  awsConfig: !file_contents /root/.aws/config
  awsCredentials: !file_contents /root/.aws/credentials
  ### monitoring stack config
  monitoringConfig: !file_contents /root/values.yaml

