Parameters:
  InstanceImage:
    Type: String
  SSHKey:
    Type: String
  VmType:
    Type: String
  SubnetPublicId:
    Type: String
  ClusterName:
    Type: String
  awsConfig:
    Type: String
  awsCredentials:
    Type: String
  BastionSecurityGroup:
    Type: String


Resources:

### Instance declaration
  BastionHost:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          install:
            - Setup
        Setup:
          files:
            /root/.aws/config:
              content:
                Ref: awsConfig
              owner: root
              group: root
              mode: '0644'
            /root/.aws/credentials:
              content:
                Ref: awsCredentials
              owner: root
              group: root
              mode: '0644'
          commands:
            '01_get_awscli':
               command: pip install awscli
               ignoreErrors: true
            '02_get_kubectl':
               command: !Sub |
                 curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
                 echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list && \
                 apt update && apt install kubectl -y
               ignoreErrors: true
            '03_config_kubectl':
               command: !Sub |
                 aws eks --region ${AWS::Region} update-kubeconfig --name $CLUSTER
               env:
                 CLUSTER:
                   Ref: ClusterName
               ignoreErrors: true
            '04_check_config':
               command: !Sub |
                 kubectl version --client > /root/nodes.txt
               ignoreErrors: true
    Properties:
      ImageId:
        Ref: InstanceImage
      KeyName:
        Ref: SSHKey
      InstanceType:
        Ref: VmType
      SecurityGroupIds:
        - Ref: BastionSecurityGroup
      SubnetId:
        Ref: SubnetPublicId
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          apt update && apt install python-pip -y
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource BastionHost --configsets install --region ${AWS::Region}
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName}   --resource BastionHost --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: Bastion-Host


